#!/usr/bin/env bash
set -e

APP_NAME=$1

if [ -z "$APP_NAME" ]; then
  echo "Usage: ./new_rails.sh app_name"
  exit 1
fi

echo "Creating Rails 8 app: $APP_NAME"

# Rubocop is skipped here to avoid version conflicts; it will be added later
rails new "$APP_NAME" \
  --database=sqlite3 \
  --skip-action-mailbox \
  --skip-action-text \
  --skip-rubocop \
  --skip-jbuilder \
  --skip-test \
  --skip-system-test \
  --javascript=importmap \
  --css=sass

cd "$APP_NAME"

echo "Adding gems..."

bundle add dartsass-rails
bundle add view_component
bundle add rubocop --group=development,test
bundle add ruby-lsp --group=development
bundle add rubocop-rails --group=development,test
bundle add rubocop-performance --group=development,test
bundle add hotwire-spark --group=development

bundle install

echo "Setting up Dart Sass..."

bin/rails dartsass:install

# Rename default stylesheet if desired
if [ -f app/assets/stylesheets/application.scss ]; then
  echo "SCSS already exists"
  rm app/assets/stylesheets/application.css
else
  mv app/assets/stylesheets/application.css app/assets/stylesheets/application.scss
fi

# ViewComponent configuration
ruby <<'RUBY'
path = "config/application.rb"
content = File.read(path)

insert = <<~CONFIG

        # ViewComponent
        config.view_component.generate.sidecar = true
        config.view_component.previews.paths << Rails.root.join("spec/components/previews")
CONFIG

content.sub!(
  /class Application < Rails::Application\n/,
  "class Application < Rails::Application\n#{insert}"
)

File.write(path, content)
RUBY

# Rake task to build view component sass files
mkdir -p lib/tasks
cat <<'EOF' > lib/tasks/components.rake
namespace :components do
  desc "Build sass components file"
  task :build_styles do
    require "fileutils"

    sass_dir = File.join("app", "assets", "stylesheets")
    components_dir = File.join("app", "components")
    output_file = File.join(sass_dir, "_components.scss")

    component_files = Dir.glob(File.join(components_dir, "**", "*.scss"))
    File.open(output_file, "w") do |output|
      output.puts "// This file is auto-generated by rake components:build_styles"
      output.puts "// Do not edit this file directly"
      output.puts
      component_files.each do |file|
        relative_path = Pathname.new(file).relative_path_from(Pathname.new(sass_dir))
        output.puts "@use '#{relative_path.to_s.sub(/\.scss$/, '')}';"
      end
    end
  end
end
EOF

# RuboCop setup
echo "Configuring RuboCop..."

cat <<EOF > .rubocop.yml
plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"

Layout/LineLength:
  Max: 100
EOF

bundle exec rubocop --auto-gen-config || true

# Font Awesome setup
echo "Configuring Font Awesome..."

cat <<EOF >> app/assets/stylesheets/application.scss

@use "font-awesome" with (
  \$fa-font-path: "font-awesome"
);
EOF

# Git init
echo "Initializing git..."

git init
git checkout -b master
git add .
git commit -m "Initial Rails 8 setup with Hotwire, ViewComponent, SASS, and tooling"

echo "Done."
echo "Next steps:"
echo "  cd $APP_NAME"
echo "  bin/dev"
