return {
--   -- Fuzzy Finder (files, lsp, etc)
--   'nvim-telescope/telescope.nvim',
--   event = 'VimEnter',
--   branch = '0.1.x',
--   dependencies = {
--     'nvim-lua/plenary.nvim',
--     { -- If encountering errors, see telescope-fzf-native README for installation instructions
--       'nvim-telescope/telescope-fzf-native.nvim',
--
--       -- `build` is used to run some command when the plugin is installed/updated.
--       -- This is only run then, not every time Neovim starts up.
--       build = 'make',
--
--       -- `cond` is a condition used to determine whether this plugin should be
--       -- installed and loaded.
--       cond = function()
--         return vim.fn.executable 'make' == 1
--       end,
--     },
--     { 'nvim-telescope/telescope-ui-select.nvim' },
--     { 'nvim-tree/nvim-web-devicons', enabled = vim.g.have_nerd_font },
--   },
--   config = function()
--     require('telescope').setup {
--       defaults = {
--         mappings = {
--           i = { ['<c-enter>'] = 'to_fuzzy_refine' },
--         },
--       },
--       pickers = {},
--       extensions = {
--         fzf = {},
--         ['ui-select'] = {
--           require('telescope.themes').get_dropdown(),
--         },
--       },
--     }
--
--     -- Enable Telescope extensions if they are installed
--     pcall(require('telescope').load_extension, 'fzf')
--     pcall(require('telescope').load_extension, 'ui-select')
--
--     -- See `:help telescope.builtin`
--     local builtin = require 'telescope.builtin'
--     local root_dir = vim.fs.dirname(vim.fs.find({ '.git', 'Gemfile' }, { upward = true })[1])
--     -- Rails custom maps
--     vim.keymap.set('n', '<leader>sv', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/views',
--       }
--     end, { desc = '[S]each [V]iews' })
--
--     vim.keymap.set('n', '<leader>sc', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/controllers',
--       }
--     end, { desc = '[S]each [C]ontrollers' })
--
--     vim.keymap.set('n', '<leader>sm', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/models',
--       }
--     end, { desc = '[S]each [M]odels' })
--
--     vim.keymap.set('n', '<leader>sj', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/javascript',
--       }
--     end, { desc = '[S]each [J]avascript' })
--
--     vim.keymap.set('n', '<leader>ss', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/assets/stylesheets',
--       }
--     end, { desc = '[S]each [S]tylesheets' })
--
--     vim.keymap.set('n', '<leader>sa', function()
--       builtin.find_files {
--         cwd = root_dir .. '/app/components',
--       }
--     end, { desc = '[S]each Components' })
--
--     vim.keymap.set('n', '<leader>sh', builtin.help_tags, { desc = '[S]earch [H]elp' })
--     vim.keymap.set('n', '<leader>sk', builtin.keymaps, { desc = '[S]earch [K]eymaps' })
--     vim.keymap.set('n', '<leader>sf', builtin.find_files, { desc = '[S]earch [F]iles' })
--     vim.keymap.set('n', '<leader>sw', builtin.grep_string, { desc = '[S]earch current [W]ord' })
--     vim.keymap.set('n', '<leader>sg', builtin.live_grep, { desc = '[S]earch by [G]rep' })
--     vim.keymap.set('n', '<leader>sd', builtin.diagnostics, { desc = '[S]earch [D]iagnostics' })
--     vim.keymap.set('n', '<leader>sr', builtin.resume, { desc = '[S]earch [R]esume' })
--     vim.keymap.set('n', '<leader><leader>', builtin.oldfiles, { desc = '[ ] Search Recent Files' })
--     vim.keymap.set('n', '<leader>s.', builtin.buffers, { desc = '[S]earch Buffers ("." for repeat)' })
--
--     -- Slightly advanced example of overriding default behavior and theme
--     vim.keymap.set('n', '<leader>/', function()
--       -- You can pass additional configuration to Telescope to change the theme, layout, etc.
--       builtin.current_buffer_fuzzy_find(require('telescope.themes').get_dropdown {
--         winblend = 10,
--         previewer = true,
--       })
--     end, { desc = '[/] Fuzzily search in current buffer' })
--
--     -- It's also possible to pass additional configuration options.
--     --  See `:help telescope.builtin.live_grep()` for information about particular keys
--     vim.keymap.set('n', '<leader>s/', function()
--       builtin.live_grep {
--         grep_open_files = true,
--         prompt_title = 'Live Grep in Open Files',
--       }
--     end, { desc = '[S]earch [/] in Open Files' })
--
--     -- Shortcut for searching your Neovim configuration files
--     vim.keymap.set('n', '<leader>sn', function()
--       builtin.find_files { cwd = vim.fn.stdpath 'config' }
--     end, { desc = '[S]earch [N]eovim files' })
--   end,
}
